--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Refaltor77/AddFoods
build-by-default: true
branches:
- main
projects:
  AddFoods:
    path: ""
    icon: resources/pack/pack_icon.png
...
